### ISSUE TITLE
What does random AI mean?

### ISSUE THREAD

**Issue by arisliang** [yhyu13/AlphaGOZero-python-tensorflow#14]
Mentioned in the README:
> Play Against An A.I. (currently only random A.I. is available)

What does random A.I. mean?

**Comment by yhyu13** [comment]
@arisliang 

It was an outdated readme. I've updated its content recently, so the command you see under this line would use MCTS+DNN policy. A random A.I. plays a move randomly, it was a quick way to see if the code (mainly Go engine) works on your machine or not because initializing a DNN takes more computer resources. Thanks for spotting my mistakes
